version: '3.8'

services:
  laravel:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: laravel-app
    ports:
      - "24103:80"
    restart: unless-stopped
    volumes:
      # Solo monta las carpetas necesarias (evita sobrescribir permisos)
      - ./bootstrap:/var/www/bootstrap
      - ./storage/logs:/var/www/storage/logs
      - ./storage/framework:/var/www/storage/framework
      - .env:/var/www/.env
    environment:
      AES_KEY: ${AES_KEY}
      CIPHER: ${CIPHER}
      IV_HEX: ${IV_HEX}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
      APP_NAME: ${APP_NAME}
      APP_ENV: ${APP_ENV}
      APP_KEY: ${APP_KEY}
      APP_DEBUG: ${APP_DEBUG}
      APP_URL: ${APP_URL}
      ASSET_URL: ${ASSET_URL}
      APP_HTTPS: ${APP_HTTPS}
      ADMIN_MAIL: ${ADMIN_MAIL}
      ADMIN_PASSWD: ${ADMIN_PASSWD}
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7.23
    container_name: laravel-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

volumes:
  dbdata:
