version: '3.8'

services:
  laravel:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: laravel-app
    ports:
      - "24103:80"
    volumes:
      # Solo monta las carpetas necesarias (evita sobrescribir permisos)
      - ./bootstrap:/var/www/bootstrap
      - ./storage/logs:/var/www/storage/logs
      - ./storage/framework:/var/www/storage/framework
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7.23
    container_name: laravel-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

volumes:
  dbdata:
